name: FreshDonate
version: '${version}'
main: ru.zaralx.freshDonatePlugin.FreshDonatePlugin
description: Donation delivery plugin for FreshDonate platform
authors: [zaralX]
website: https://zaralx.ru

commands:
  freshdonate:
    description: FreshDonate admin commands
    permission: freshdonate.admin
    aliases: [fd]

permissions:
  freshdonate.admin:
    description: Access to FreshDonate admin commands
    default: op
